FROM openjdk:11
EXPOSE 8081
ARG AWS_ACCESS_KEY
ENV AWS_ACCESS_KEY_ENV=${MI_AWS_ACCESS_KEY}

ARG AWS_SECRET_KEY
ENV AWS_SECRET_KEY_ENV=${MI_AWS_SECRET_KEY}

ARG DB_RDS_PASSWORD
ENV DB_RDS_PASSWORD_ENV=${MI_DB_RDS_PASSWORD}

ARG DB_USERS_RDS_URL
ENV DB_USERS_RDS_URL_ENV=${MI_DB_USERS_RDS_URL}

ARG DB_USERS_RDS_USERNAME
ENV DB_USERS_RDS_USERNAME_ENV=${MI_DB_USERS_RDS_USERNAME}

ADD build/libs/users-api-0.0.1-SNAPSHOT.jar /app/users-api-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/app/users-api-0.0.1-SNAPSHOT.jar"]